//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVC01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int ID { get; set; }
        public string bookNum { get; set; }
        public string bookName { get; set; }
        public string bookConcern { get; set; }
        public string bookAuthor { get; set; }
        public int bookCount { get; set; }
        public decimal bookPrice { get; set; }
    }
}
